// /src/components/ExecutiveSummary.jsx
import { AlertTriangle, Award, Gauge } from 'lucide-react';
import { percent } from '../utils/formatters';

export default function ExecutiveSummary({ summary, siteKPIs, redFlags, usingMock }) {
  const best = siteKPIs[0];
  const lowest = [...siteKPIs].sort((a, b) => a.utilization - b.utilization)[0];
  return (
    <div className="space-y-4">
      {usingMock && (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">
          Mock data is currently displayed. Click “Load Test Files” or upload real Tableau Excel reports for live analysis.
        </div>
      )}
      <div className="rounded-3xl bg-gradient-to-br from-hpNavy to-hpBlue p-5 sm:p-6 text-white">
        <p className="text-xs font-bold uppercase tracking-[0.2em] text-sky-100">Executive Summary</p>
        <p className="mt-3 text-base sm:text-lg leading-8">{summary}</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="rounded-2xl border border-green-100 bg-green-50 p-4">
          <Award className="text-green-700" />
          <p className="mt-2 text-sm text-green-700 font-bold">Best Site</p>
          <p className="text-xl font-black text-green-900">{best?.callCenter || 'N/A'}</p>
          <p className="text-sm text-green-800">{percent(best?.utilization || 0)} utilization</p>
        </div>
        <div className="rounded-2xl border border-red-100 bg-red-50 p-4">
          <Gauge className="text-red-700" />
          <p className="mt-2 text-sm text-red-700 font-bold">Lowest Productivity</p>
          <p className="text-xl font-black text-red-900">{lowest?.callCenter || 'N/A'}</p>
          <p className="text-sm text-red-800">{percent(lowest?.utilization || 0)} utilization</p>
        </div>
        <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4">
          <AlertTriangle className="text-amber-700" />
          <p className="mt-2 text-sm text-amber-700 font-bold">Risk Signals</p>
          <p className="text-xl font-black text-amber-900">{redFlags.length}</p>
          <p className="text-sm text-amber-800">flags generated by the rule engine</p>
        </div>
      </div>
    </div>
  );
}
